files:
  include: src/scss/**/*.scss
  ignore: src/scss/tachyons/*.scss
options:
  formatter: stylish
  merge-default-rules: true
rules:
  class-name-format: 0
  function-name-format: 0
  hex-notation: 0
  id-name-format: 0
  leading-zero: 0
  mixin-name-format: 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-literals: 0
  no-important: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  placeholder-name-format: 0
  property-sort-order: 0
  url-quotes: 0
  variable-name-format: 0
